// @generated by pi-protocol generate; DO NOT EDIT.
// contract-digest: sha256:c8e51c95a5ec4ee17c7563c26f8f3f7fec6f83013ca36b1616348e9eb329fbca
import type { ProtocolAgentExecutor, ProtocolHandler } from "@kybernetria/pi-protocol/core";

export const PROTOCOL_NODE_ID = "pi_full_session" as const;
export const PROTOCOL_TARGETS = {
  launch: "pi_full_session.launch",
} as const;

export type ProtocolProvideName = "launch";
export type ProtocolBinding = ProtocolHandler | ProtocolAgentExecutor;
export type ProtocolBindings = {
  "launch": ProtocolBinding;
};

export type LaunchInput = { cwd: string; initialPrompt?: string; name?: string; };
export type LaunchOutput = { cwd: string; launched: true; piSessionId: string; };
