// @generated by pi-protocol generate; DO NOT EDIT.
// contract-digest: sha256:e65f382fffc720616178bb05080a7599f4d44f333d6f68c825f5d2b32ac76125
import type { ProtocolAgentExecutor, ProtocolHandler } from "@kybernetria/pi-protocol/core";

export const PROTOCOL_NODE_ID = "pi_full_session" as const;
export const PROTOCOL_TARGETS = {
  launch: "pi_full_session.launch",
} as const;

export type ProtocolProvideName = "launch";
export type ProtocolBinding = ProtocolHandler | ProtocolAgentExecutor;
export type ProtocolBindings = {
  "launch": ProtocolBinding;
};

export type LaunchInput = { cwd: string; initialPrompt?: string; name?: string; };
export type LaunchOutput = { cwd: string; launched: true; piSessionId: string; };
